[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I", "B", "UP", "N", "PL", "RUF"]
ignore = ["E203"]

[tool.ruff.isort]
known-first-party = ["app"]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_any_generics = true
no_implicit_optional = true
check_untyped_defs = true
strict_optional = true
pretty = true
show_error_codes = true
exclude = [
    "migrations/",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

